SELECT
CITY
FROM STATION
WHERE (ASCII(CITY) = 65 OR ASCII(CITY) = 69 OR ASCII(CITY) = 73 OR ASCII(CITY) = 79 OR ASCII(CITY) = 85) AND (RIGHT(CITY,1) = 'a' OR RIGHT(CITY,1) = 'e' OR RIGHT(CITY,1) = 'i' OR RIGHT(CITY,1) = 'o' OR RIGHT(CITY,1) = 'u')