SELECT
CITY
FROM STATION
WHERE (RIGHT(CITY,1) <> 'a' AND RIGHT(CITY,1) <> 'e' AND RIGHT(CITY,1) <> 'i' AND RIGHT(CITY,1) <> 'o' AND RIGHT(CITY,1) <> 'u') OR (ASCII(CITY) <> 65 AND ASCII(CITY) <> 69 AND ASCII(CITY) <> 73 AND ASCII(CITY) <> 79 AND ASCII(CITY) <> 85)
GROUP BY CITY